I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 19, in script
    scene bg room zoom 2
Exception: Image 'bg room' does not accept attributes 'zoom 2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 19, in script
    scene bg room zoom 2
  File "C:\Users\thesc\Documents\renpy-8.3.4-sdk\renpy\ast.py", line 1251, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\thesc\Documents\renpy-8.3.4-sdk\renpy\ast.py", line 1080, in show_imspec
    renpy.config.show(name,
  File "C:\Users\thesc\Documents\renpy-8.3.4-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\thesc\Documents\renpy-8.3.4-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\thesc\Documents\renpy-8.3.4-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Users\thesc\Documents\renpy-8.3.4-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'bg room' does not accept attributes 'zoom 2'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.4.24120703
OverDate 1.0
Thu Feb 27 23:56:09 2025
